Repository hasso-plattner-institute/scihfs, pull requests merged in 2024-12, with the labels that each got.

#20 Removed real-world data (HAGR+GO) data from repository
  data/dataset_go_hagr.py
  data/go_hagr/datasets/dataset_Caenorhabditis elegans.npz
  data/go_hagr/datasets/dataset_Drosophila melanogaster.npz
  data/go_hagr/datasets/dataset_Mus musculus.npz
  data/go_hagr/datasets/dataset_Saccharomyces cerevisiae.npz
  data/go_hagr/datasets/go_dag.gml
Labels: improvement, good first issue

#36 Refactor extend dag
  Makefile
  hfs/helpers.py
  hfs/preprocessing.py
  hfs/selectors/base.py
  hfs/selectors/eagerHierarchicalFeatureSelector.py
  hfs/selectors/gtd.py
  hfs/selectors/hie_aode.py
  hfs/selectors/hill_climbing.py
  hfs/selectors/hip.py
  hfs/selectors/hnb.py
  hfs/selectors/lazyHierarchicalFeatureSelector.py
  hfs/selectors/mr.py
  hfs/selectors/shsel.py
  hfs/selectors/tsel.py
  hfs/tests/test_base.py
  hfs/tests/test_common.py
  hfs/tests/test_feature_selection_filter.py
  hfs/tests/test_helpers.py
  hfs/tests/test_hie_aode.py
  hfs/tests/test_preprocessing.py
  poetry.lock
Labels: improvement, fundamentals

#40 Check input DAG
  hfs/helpers.py
  hfs/preprocessing.py
Labels: improvement, fundamentals, new feature
